export const ADVERTS_CREATED_REQUEST = 'ADVERTS_CREATED_REQUEST';
export const ADVERTS_CREATED_SUCCESS = 'ADVERTS_CREATED_SUCCESS';
export const ADVERTS_CREATED_FAILURE = 'ADVERTS_CREATED_FAILURE';


